### ISSUE TITLE
Tensorrt8.0 explicit  quantization accuracy issue

### ISSUE THREAD

**Issue by wenhuach** [NVIDIA/TensorRT#1374]
Hi,
I am trying the explicit quantization feature on Yolov5s model. when I tried the specific model attached below,  the mAP measured differed a lot bettween onnx with trt，~36.0% vs 0.0%.
[yolov5s_quant_example.onnx.zip](https://github.com/NVIDIA/TensorRT/files/6820144/yolov5s_quant_example.onnx.zip)

Thanks in advance.

Environment:
TensorRT Version: 8.0.0.3
NVIDIA GPU: T4
NVIDIA Driver Version:
CUDA Version: 11.0
CUDNN Version: 8..0
Operating System: Ubuntu 18.04

**Comment by ttyio** [comment]
Hello @wenhuach , this should be fixed in 8.0 GA, could you upgrade your TRT? thanks!

**Comment by wenhuach** [comment]
> Hello @wenhuach , this should be fixed in 8.0 GA, could you upgrade your TRT? thanks!

Hi @ttyio, thanks for the reply. Actually, I had tested it on 8.0.1.6  before I submitted this issue. And  I just tested it again, the issue still exists.

**Comment by nvpohanh** [comment]
@wenhuach Could you try TRT 8.4 and see if the issue still exists? If so, we will debug this. Thanks

**Comment by ttyio** [comment]
closing due to no activity for more than 3 weeks, please reopen if you still have question, thanks!
