### ISSUE TITLE
About CPU Problems

### ISSUE THREAD

**Issue by M15-3080** [NVIDIA/TensorRT#2412]
## Description

In the case of the same CUDA and TensorRT configuration, the graphics card also has the same configuration.  CPU Core processor and Xeon processor, in the reasoning produced a large gap, CPU is i7-11700F and E5 2680 V4 
 
Hopecan get help, thank you

**Comment by zerollzeng** [comment]
It's hard to say the exact reason without a clear reproduce. 

Some models is kernel-launch-bounded, e.g. a model with lots of small kernel and the time is mainly consume by CPU launch, I would suggest to use CUDA Graph in this case(trtexec has an option to enable cuda graph quickly for performance test).

**Comment by M15-3080** [comment]
> 如果没有明确的复制，很难说确切的原因。
> 
> 有些模型是内核启动绑定的，例如一个有很多小内核的模型，时间主要由 CPU 启动消耗，我建议在这种情况下使用 CUDA 图（trtexec 有一个选项可以快速启用 cuda 图进行性能测试）。

非常感谢您的回复。酷睿处理器i7-11700F有8个内核，至强处理器E5 2680 V4有16个内核。但是同一个模型文件，酷睿CPU生成引擎模型只需要10分钟左右，而至强处理器却要花费一个多小时。

**Comment by zerollzeng** [comment]
@nvpohanh Do you have any idea abut this issue? thanks!

**Comment by M15-3080** [comment]
> @nvpohanh你对这个问题有什么想法吗？谢谢！

Why does it take longer to load the engine with more cpus?

**Comment by nvpohanh** [comment]
are you referring to the time taken to build the engine? Or the time taken to run inference?

I would expect E5 2680 to be much faster than i7 for engine building phase. Could you share verbose log so that we can see where it got stuck at?

**Comment by M15-3080** [comment]
> 你指的是制造引擎所需的时间吗？还是运行推理所花费的时间？
> 
> 我希望E5 2680在发动机制造阶段比i7快得多。您能否分享详细的日志，以便我们可以看到它卡在哪里？

Building the engine and running reasoning is much slower than the i7

**Comment by nvpohanh** [comment]
Could you share the trtexec verbose logs so that we can investigate this?

**Comment by M15-3080** [comment]
> 

Sorry, I didn't use the trtexec command, I used my YOLO trained pt model, converted it into wts, and then converted it into engine (when regenerated into engine, 3080Ti and 3080 took 1 hour, while TITANV only took a few minutes)

**Comment by nvpohanh** [comment]
oh, then it's not because of the CPU. It's because for 3080/3080Ti, there are many more options for data types for formats, so the engine building time would increase compared to TITAN V. If you want to reduce this time, you can try enabling the `ENABLE_TACTIC_HEURISTIC` flag https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.BuilderFlag ? It allows TRT to use some heuristics when selecting tactics. The resulting engine may be slightly suboptimal, but the engine building time will be much faster.

**Comment by M15-3080** [comment]
> 哦，那不是因为 CPU。这是因为对于 3080/3080Ti，格式的数据类型有更多的选择，因此与 TITAN V 相比，引擎构建时间会增加。如果你想减少这个时间，你可以尝试启用标志https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.BuilderFlag？它允许 TRT 在选择策略时使用一些启发式方法。由此产生的引擎可能略微欠佳，但引擎制造时间会快得多。`ENABLE_TACTIC_HEURISTIC`

However, when I used the 3080 and 3080Ti, both the reasoning time and the detection time were much slower than TITANV. Other configurations of the computer were the same, but the graphics card was changed

**Comment by nvpohanh** [comment]
> However, when I used the 3080 and 3080Ti, both the reasoning time and the detection time were much slower than TITANV. Other configurations of the computer were the same, but the graphics card was changed

If this is the case, then it would be great if you can provide the repro steps so that we can debug this perf issue. Thanks

**Comment by M15-3080** [comment]
> > 但是，当我使用3080和3080Ti时，推理时间和检测时间都比TITANV慢得多。计算机的其他配置相同，但显卡已更改
> 
> 如果是这种情况，那么如果您可以提供重现步骤，以便我们可以调试此性能问题，那就太好了。谢谢

I would like to provide the steps, but I don't know how to do it. What method should I use?

**Comment by nvpohanh** [comment]
Do you use ONNX file to build TensorRT engine? If so, you can try using the `trtexec` tool with the ONNX file to measure the inference performance.

**Comment by nvpohanh** [comment]
I see. Or you can run `trexec --loadEngine=/path/to/engine --noDataTransfers --useCudaGraph --useSpinWait --dumpLayerInfo --dumpProfile --separateProfileRun` and share the logs? If possible, please also share Nsight Systems profiles: `nsys profile -o <OUTPUT_PROFILE> trexec --loadEngine=/path/to/engine --noDataTransfers --useSpinWait --iterations=20 --duration=0 --warmUp=0`

**Comment by M15-3080** [comment]
> 明白了。或者您可以运行和共享日志？如果可能，请同时分享Nsight Systems的个人资料：`trexec --loadEngine=/path/to/engine --noDataTransfers --useCudaGraph --useSpinWait --dumpLayerInfo --dumpProfile --separateProfileRun``nsys profile -o <OUTPUT_PROFILE> trexec --loadEngine=/path/to/engine --noDataTransfers --useSpinWait --iterations=20 --duration=0 --warmUp=0`

Ok, I'll test it as soon as possible，thanks

**Comment by M15-3080** [comment]
> 明白了。或者您可以运行和共享日志？如果可能，请同时分享Nsight Systems的个人资料：`trexec --loadEngine=/path/to/engine --noDataTransfers --useCudaGraph --useSpinWait --dumpLayerInfo --dumpProfile --separateProfileRun``nsys profile -o <OUTPUT_PROFILE> trexec --loadEngine=/path/to/engine --noDataTransfers --useSpinWait --iterations=20 --duration=0 --warmUp=0`

Hello, I entered according to your specified command, the parameter is still disabled by default, and the engine cannot be generated
![image](https://user-images.githubusercontent.com/91411583/205793483-77ecd1c5-3198-4f8e-ac7f-8314fda68d40.png)

**Comment by nvpohanh** [comment]
Several issues in the command:

- `wprkspace` should be `workspace`
- `1*3*1280*1280` should be `1x3x1280x1280`

**Comment by M15-3080** [comment]
> 命令中的几个问题：
> 
> * `wprkspace`应该是`workspace`
> * `1*3*1280*1280`应该是`1x3x1280x1280`

Thank you. I tried again
![image](https://user-images.githubusercontent.com/91411583/205804202-5dbcd155-10d7-4a59-b229-67d9cc261f9d.png)

**Comment by nvpohanh** [comment]
It seems that TRT crashed because it cannot find the proper dependencies (like CUDNN, cuBLAS, etc.). Could you make sure those dependencies are correctly installed and has been added to `%PATH%`?

Also, it seems that you are using TRT 7.2. Is it possible to try with newer TRT version? TRT 7.2 does NOT support 3080/3080Ti GPUs.

**Comment by M15-3080** [comment]
> 命令中的几个问题：
> 
> * `wprkspace`应该是`workspace`
> * `1*3*1280*1280`应该是`1x3x1280x1280`

I use order：trtexec --onnx=int32.onnx --saveEngine=best.engine --workspace=4096 --minShapes=input:1x3x1280x1280 --optShapes=input:1x3x1280x1280 --maxShapes=input:1x3x1280x1280 --fp16.  Unable to generate engine.

**Comment by M15-3080** [comment]
> TRT似乎崩溃了，因为它找不到正确的依赖项（如CUDNN，cuBLAS等）。您能否确保这些依赖项已正确安装并已添加到？`%PATH%`
> 
> 另外，您似乎正在使用TRT 7.2。是否可以尝试使用较新的 TRT 版本？TRT 7.2 不支持 3080/3080Ti GPU。

I see. I'll try using TensorRT8.2 again

**Comment by M15-3080** [comment]
> TRT似乎崩溃了，因为它找不到正确的依赖项（如CUDNN，cuBLAS等）。您能否确保这些依赖项已正确安装并已添加到？`%PATH%`
> 
> 另外，您似乎正在使用TRT 7.2。是否可以尝试使用较新的 TRT 版本？TRT 7.2 不支持 3080/3080Ti GPU。

I'm currently using a TITANV graphics card and TensorRT version 8.2.4.2
![image](https://user-images.githubusercontent.com/91411583/205807227-a4120896-a5e8-4296-a5f4-03b3f8e244ef.png)

**Comment by M15-3080** [comment]
> TRT似乎崩溃了，因为它找不到正确的依赖项（如CUDNN，cuBLAS等）。您能否确保这些依赖项已正确安装并已添加到？`%PATH%`
> 
> 另外，您似乎正在使用TRT 7.2。是否可以尝试使用较新的 TRT 版本？TRT 7.2 不支持 3080/3080Ti GPU。

I replaced my graphics card and am currently using 3080Ti and TensorRT version 8.2，I put the onnx file in the bin folder.TensorRT8.2 has been tested and is successful
![image](https://user-images.githubusercontent.com/91411583/205830271-fa222499-59b3-4268-8891-a779584a7721.png)

**Comment by nvpohanh** [comment]
`saceEngine` -> `saveEngine`

**Comment by M15-3080** [comment]
> `saceEngine` -> `saveEngine`

Have been corrected
![image](https://user-images.githubusercontent.com/91411583/205836464-fa2112f9-97b8-4a00-bc63-d00a12f3d2a8.png)

**Comment by M15-3080** [comment]
> `saceEngine` -> `saveEngine`

I have been failing with the trtexec command generation engine, but I can use the c++ program generation engine; If I have a 3080TI and TitanV generation engine, do I need to use Nsight Systems software for visual comparison? Sorry to bother you all the time, my programming ability is weak, thank you very much!

**Comment by nvpohanh** [comment]
It seems that `trtexec` is still crashing....

> If I have a 3080TI and TitanV generation engine, do I need to use Nsight Systems software for visual comparison?

Yes, having Nsight systems profiles will be very useful for us to debug this.

**Comment by ttyio** [comment]
Closing since no activity for more than 3 weeks, please reopen if you still have question, thanks!
